# Generated by Django 5.0.4 on 2024-05-02 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='make',
        ),
    ]
