# Generated by Django 5.0.4 on 2024-05-02 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher_desc',
        ),
    ]
